name: sentiric_mobile
description: "Sentiric Mobile Platform: Agent, Supervisor, and Customer Cockpit."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0' # Modern Dart 3 özelliklerini destekler

dependencies:
  flutter:
    sdk: flutter

  # --- UI & Styling ---
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1     # Profesyonel ve tutarlı tipografi için.

  # --- State Management (Durum Yönetimi) ---
  flutter_riverpod: ^2.5.1  # Modern, güvenli ve ölçeklenebilir bir state management çözümü.
  riverpod_annotation: ^2.3.5 # Riverpod için kod üretimini kolaylaştırır.

  # --- Routing (Sayfa Yönlendirme) ---
  go_router: ^14.2.0        # URL tabanlı, güçlü ve modern bir yönlendirme çözümü.

  # --- API & Networking ---
  http: ^1.2.1              # api-gateway'e REST çağrıları yapmak için.

  # --- Utility (Yardımcı Paketler) ---
  shared_preferences: ^2.2.3 # Kullanıcının tema gibi basit tercihlerini saklamak için.
  
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0     # Kod kalitesini yüksek tutmak için lint kuralları.
  
  # --- Kod Üretimi (Code Generation) ---
  # Riverpod provider'larını otomatik olarak oluşturur, yazım hatalarını azaltır.
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11


flutter:
  uses-material-design: true

  # --- Assets (Görsel Varlıklar) ---
  # 'assets/' klasöründeki tüm dosyaları uygulamaya dahil et.
  # Bu, logolarınızı kullanabilmemizi sağlar.
  assets:
    - assets/